// =============================================================================
// Chat Grounding — persona-specific chart-fact slices for the AI astrologer
// =============================================================================
// Minimum-necessary-data discipline: each persona receives only the derived
// facts relevant to its domain (never the raw name/DOB/place, never the full
// planetary degree table). The LLM's job is narration, never arithmetic —
// every number here comes from the user's already-computed, stored kundli.
// =============================================================================

import { dashaLordTransitQuality, SIGNS } from './astro-tools/index.js';
import { dateToJulianDay, calculatePlanetPositions } from './astro-engine/index.js';

export type ChatPersona = 'career' | 'love' | 'health' | 'general';

export interface GroundingSource {
  /** kundli.chartData — planets, houses (with lord), ascendant. */
  chart: Record<string, unknown> | null;
  /** kundli.dashaData — { vimshottari: VimshottariDasha }. */
  dasha: Record<string, unknown> | null;
  /** kundli.yogaData — { yogas: Yoga[] }. */
  yogas: Record<string, unknown> | null;
  /** kundli.doshaData — DoshaAnalysis (mangal, kaalSarp, sadeSati, ...). */
  doshas: Record<string, unknown> | null;
}

interface HouseFact {
  house: number;
  lord: string;
  sign: string;
}

interface PlanetFact {
  planet: string;
  sign: string;
  signIndex: number;
  house: number;
}

function getHouses(chart: Record<string, unknown> | null): HouseFact[] {
  const houses = (chart?.houses ?? []) as Array<Record<string, unknown>>;
  return houses
    .filter((h) => h.house != null && h.lord != null)
    .map((h) => ({ house: Number(h.house), lord: String(h.lord), sign: String(h.sign ?? '') }));
}

function getPlanets(chart: Record<string, unknown> | null): PlanetFact[] {
  const planets = (chart?.planets ?? []) as Array<Record<string, unknown>>;
  return planets
    .filter((p) => p.planet != null)
    .map((p) => ({
      planet: String(p.planet),
      sign: String(p.sign ?? ''),
      signIndex: Number(p.signIndex ?? 0),
      house: Number(p.house ?? 0),
    }));
}

function houseLord(houses: HouseFact[], houseNum: number): HouseFact | undefined {
  return houses.find((h) => h.house === houseNum);
}

function planetPlacement(planets: PlanetFact[], planetName: string): PlanetFact | undefined {
  return planets.find((p) => p.planet === planetName);
}

interface CurrentDasha {
  mahadasha?: string | undefined;
  antardasha?: string | undefined;
  mahaStart?: string | undefined;
  mahaEnd?: string | undefined;
}

function currentDasha(dasha: Record<string, unknown> | null): CurrentDasha {
  const v = (dasha?.vimshottari ?? {}) as Record<string, unknown>;
  const md = v.currentMahadasha as Record<string, unknown> | undefined;
  const ad = v.currentAntardasha as Record<string, unknown> | undefined;
  return {
    mahadasha: md?.planet ? String(md.planet) : undefined,
    antardasha: ad?.planet ? String(ad.planet) : undefined,
    mahaStart: md?.startDate ? String(md.startDate).slice(0, 10) : undefined,
    mahaEnd: md?.endDate ? String(md.endDate).slice(0, 10) : undefined,
  };
}

/** Present, typed yogas (Raja/Dhana by default) touching any of the given houses. */
function relevantYogas(
  yogas: Record<string, unknown> | null,
  houses: number[],
  types: string[] = ['dhana', 'raja'],
): string[] {
  const list = (yogas?.yogas ?? []) as Array<Record<string, unknown>>;
  return list
    .filter((y) => {
      if (!y.present || !types.includes(String(y.type))) return false;
      const yogaHouses = Array.isArray(y.houses) ? (y.houses as number[]) : [];
      return yogaHouses.some((h) => houses.includes(h));
    })
    .map((y) => String(y.description ?? y.name ?? ''))
    .filter(Boolean);
}

async function currentTransitSignIndex(planet: string): Promise<number | null> {
  try {
    const now = new Date();
    const jd = await dateToJulianDay(
      now.getUTCFullYear(),
      now.getUTCMonth() + 1,
      now.getUTCDate(),
      now.getUTCHours(),
      now.getUTCMinutes(),
      0,
    );
    const positions = (await calculatePlanetPositions(jd)) as unknown as Array<
      Record<string, unknown>
    >;
    const p = positions.find((x) => x.planet === planet);
    return p ? Number(p.signIndex) : null;
  } catch {
    return null; // best-effort — a missing transit fact is fine, an invented one is not
  }
}

/**
 * Build the persona-specific "CHART DATA" fact lines. Every line is traceable
 * to a value already present in the user's stored kundli (or, for the current
 * transit line, a fresh planet-position calculation) — nothing here is
 * generated by an LLM.
 */
export async function buildGroundingFacts(
  src: GroundingSource,
  persona: ChatPersona,
): Promise<string[]> {
  const houses = getHouses(src.chart);
  const planets = getPlanets(src.chart);
  const dasha = currentDasha(src.dasha);
  const facts: string[] = [];

  if (dasha.mahadasha) {
    const range =
      dasha.mahaStart && dasha.mahaEnd
        ? ` (started ${dasha.mahaStart}, ends ${dasha.mahaEnd})`
        : '';
    const antar = dasha.antardasha ? ` / ${dasha.antardasha} Antardasha` : '';
    facts.push(`Active Dasha: ${dasha.mahadasha} Mahadasha${antar}${range}`);
  }

  if (persona === 'career') {
    const tenth = houseLord(houses, 10);
    const tenthLord = tenth?.lord;
    if (tenth) {
      facts.push(`10th house sign: ${tenth.sign}, lord: ${tenth.lord}`);
      const placement = planetPlacement(planets, tenth.lord);
      if (placement) {
        const dignity = dashaLordTransitQuality(tenth.lord, placement.signIndex);
        facts.push(
          `${tenth.lord} (10th lord) is natally placed in house ${placement.house} (${placement.sign}) — ${dignity.dignity} dignity`,
        );
      }
    }
    const saturnSignIdx = await currentTransitSignIndex('Saturn');
    if (saturnSignIdx != null) {
      const q = dashaLordTransitQuality('Saturn', saturnSignIdx);
      facts.push(
        `Saturn is currently transiting ${SIGNS[saturnSignIdx]} — ${q.dignity} dignity (career timing signal)`,
      );
    }
    for (const y of relevantYogas(src.yogas, [2, 6, 10, 11])) facts.push(`Relevant Yoga: ${y}`);

    // Timing signal: is the currently-active dasha lord a career significator
    // (10th lord, or a planet natally placed in the 10th house)?
    const tenthOccupants = planets.filter((p) => p.house === 10).map((p) => p.planet);
    const activeLordsCareer = [
      ...new Set([dasha.mahadasha, dasha.antardasha].filter(Boolean)),
    ] as string[];
    for (const lord of activeLordsCareer) {
      const role =
        lord === tenthLord
          ? '10th house lord'
          : tenthOccupants.includes(lord)
            ? 'natally placed in the 10th house'
            : null;
      if (role) {
        facts.push(
          `Currently active dasha lord ${lord} is also the ${role} — a traditionally significant window for career matters`,
        );
      }
    }
  } else if (persona === 'love') {
    const seventh = houseLord(houses, 7);
    const seventhLord = seventh?.lord;
    if (seventh) {
      facts.push(`7th house sign: ${seventh.sign}, lord: ${seventh.lord}`);
      const placement = planetPlacement(planets, seventh.lord);
      if (placement) {
        const dignity = dashaLordTransitQuality(seventh.lord, placement.signIndex);
        facts.push(
          `${seventh.lord} (7th lord) is natally placed in house ${placement.house} (${placement.sign}) — ${dignity.dignity} dignity`,
        );
      }
    }
    const venus = planetPlacement(planets, 'Venus');
    if (venus) {
      const dignity = dashaLordTransitQuality('Venus', venus.signIndex);
      facts.push(
        `Venus is natally in ${venus.sign} (house ${venus.house}) — ${dignity.dignity} dignity`,
      );
    }
    const mangal = src.doshas?.mangal as Record<string, unknown> | undefined;
    if (mangal) {
      facts.push(
        mangal.present
          ? `Mangal Dosha: present (${String(mangal.severity)}, ${String(mangal.type)})`
          : 'Mangal Dosha: not present',
      );
    }
    for (const y of relevantYogas(src.yogas, [7])) facts.push(`Relevant Yoga: ${y}`);

    // Timing signal 1: is the currently-active dasha lord a marriage
    // significator (7th lord, Venus, or a planet natally placed in the 7th
    // house)? Vedic timing convention checks this before anything else.
    const seventhOccupants = planets.filter((p) => p.house === 7).map((p) => p.planet);
    const activeLords = [
      ...new Set([dasha.mahadasha, dasha.antardasha].filter(Boolean)),
    ] as string[];
    for (const lord of activeLords) {
      const role =
        lord === seventhLord
          ? '7th house lord'
          : lord === 'Venus'
            ? 'natural relationship significator'
            : seventhOccupants.includes(lord)
              ? 'natally placed in the 7th house'
              : null;
      if (role) {
        facts.push(
          `Currently active dasha lord ${lord} is also the ${role} — a traditionally significant window for relationship/marriage matters`,
        );
      }
    }

    // Timing signal 2: Jupiter's current transit house-from-Ascendant — the
    // classic marriage-timing check (2nd/5th/7th/9th/11th from Lagna is
    // traditionally favorable). Mirrors the career persona's Saturn-transit
    // check below; love previously had no equivalent transit-timing signal.
    const asc = src.chart?.ascendant as Record<string, unknown> | undefined;
    const ascSignIdx = asc?.signIndex != null ? Number(asc.signIndex) : null;
    if (ascSignIdx != null) {
      const jupiterSignIdx = await currentTransitSignIndex('Jupiter');
      if (jupiterSignIdx != null) {
        const houseFromAsc = ((jupiterSignIdx - ascSignIdx + 12) % 12) + 1;
        const favorable = [2, 5, 7, 9, 11].includes(houseFromAsc);
        facts.push(
          `Jupiter is currently transiting your ${houseFromAsc}th house from the Ascendant — ${
            favorable
              ? 'traditionally favorable for relationship/marriage timing'
              : 'not one of the classic favorable houses for relationship timing right now'
          }`,
        );
      }
    }
  } else if (persona === 'health') {
    const sixEightTwelveLords: string[] = [];
    for (const houseNum of [6, 8, 12]) {
      const h = houseLord(houses, houseNum);
      if (!h) continue;
      facts.push(`${houseNum}th house sign: ${h.sign}, lord: ${h.lord}`);
      sixEightTwelveLords.push(h.lord);
    }
    const mars = planetPlacement(planets, 'Mars');
    if (mars) facts.push(`Mars is natally in house ${mars.house} (${mars.sign})`);
    const saturn = planetPlacement(planets, 'Saturn');
    if (saturn) facts.push(`Saturn is natally in house ${saturn.house} (${saturn.sign})`);

    // Timing signal 1: is the currently-active dasha lord linked to the
    // 6th/8th/12th houses (lord or natal occupant)? Extends the old
    // Mahadasha-only, lord-only check to also cover Antardasha and occupants.
    const sixEightTwelveOccupants = planets
      .filter((p) => [6, 8, 12].includes(p.house))
      .map((p) => p.planet);
    const activeLordsHealth = [
      ...new Set([dasha.mahadasha, dasha.antardasha].filter(Boolean)),
    ] as string[];
    for (const lord of activeLordsHealth) {
      if (sixEightTwelveLords.includes(lord) || sixEightTwelveOccupants.includes(lord)) {
        facts.push(
          `Currently active dasha lord (${lord}) is linked to the 6th/8th/12th houses — traditionally a period to pay closer attention to health`,
        );
      }
    }

    // Timing signal 2: Sade Sati (Saturn's 7.5-year transit over the natal
    // Moon sign) — the single most-referenced traditional health-timing
    // indicator in Vedic astrology. Already computed into doshaData elsewhere
    // (doshas/sadeSati.ts) but was never surfaced to this persona before.
    const sadeSati = src.doshas?.sadeSati as Record<string, unknown> | undefined;
    if (sadeSati?.phase && sadeSati.phase !== 'none') {
      facts.push(
        `Sade Sati: ${String(sadeSati.phase)} phase (Saturn's 7.5-year transit over the Moon sign) — traditionally a period calling for extra care and resilience`,
      );
    }
  } else {
    // general — summarized, not the raw planetary degree table
    const activeYogas = ((src.yogas?.yogas ?? []) as Array<Record<string, unknown>>)
      .filter((y) => y.present)
      .slice(0, 3)
      .map((y) => String(y.name));
    if (activeYogas.length > 0) facts.push(`Key Yogas: ${activeYogas.join(', ')}`);
    const asc = src.chart?.ascendant as Record<string, unknown> | undefined;
    if (asc?.sign) facts.push(`Ascendant: ${String(asc.sign)}`);
  }

  return facts;
}
