import { createRoute, OpenAPIHono, z } from '@hono/zod-openapi';
import { requireUser } from '../../middleware/auth.js';
import { HoroscopeSchema } from './horoscope.schemas.js';
import { getHoroscopeForUser, toHoroscopeDto } from './horoscope.service.js';

const ErrorSchema = z
  .object({
    error: z.object({
      code: z.string(),
      message: z.string(),
      details: z.unknown().optional(),
      requestId: z.string().optional(),
    }),
  })
  .openapi('Error');

const errorResponse = (description: string) => ({
  description,
  content: { 'application/json': { schema: ErrorSchema } },
});

export const horoscopeRouter = new OpenAPIHono();

horoscopeRouter.use('*', requireUser);

const getHoroscopeRoute = createRoute({
  method: 'get',
  path: '/horoscope',
  tags: ['Horoscope'],
  summary: "Get the current user's horoscope for today",
  description: "Returns today's (IST) personalized horoscope, generated by the daily CRON job.",
  security: [{ bearerAuth: [] }],
  responses: {
    200: {
      description: "Today's horoscope",
      content: { 'application/json': { schema: HoroscopeSchema } },
    },
    404: errorResponse('No horoscope available for today yet'),
    401: errorResponse('Unauthorized'),
  },
});

horoscopeRouter.openapi(getHoroscopeRoute, async (c) => {
  const user = c.get('user');
  const row = await getHoroscopeForUser(user.id);
  if (!row) {
    return c.json(
      {
        error: {
          code: 'NOT_FOUND',
          message: 'No horoscope available for today yet. Please check back shortly.',
        },
      },
      404,
    );
  }
  return c.json(toHoroscopeDto(row), 200);
});
