import { createRoute, OpenAPIHono, z } from '@hono/zod-openapi';
import { requireUser } from '../../middleware/auth.js';
import { GetHoroscopeQuerySchema, HoroscopeSchema } from './horoscope.schemas.js';
import {
  getHoroscopeForUser,
  getOrGenerateHoroscope,
  toHoroscopeDto,
} from './horoscope.service.js';

const ErrorSchema = z
  .object({
    error: z.object({
      code: z.string(),
      message: z.string(),
      details: z.unknown().optional(),
      requestId: z.string().optional(),
    }),
  })
  .openapi('Error');

const errorResponse = (description: string) => ({
  description,
  content: { 'application/json': { schema: ErrorSchema } },
});

export const horoscopeRouter = new OpenAPIHono();

horoscopeRouter.use('*', requireUser);

const getHoroscopeRoute = createRoute({
  method: 'get',
  path: '/horoscope',
  tags: ['Horoscope'],
  summary: "Get the current user's personalized horoscope",
  description:
    'Daily is generated by the nightly CRON (IST) — 404 if not ready yet. ' +
    'Weekly/monthly/yearly are generated on first request per period and cached from then on.',
  security: [{ bearerAuth: [] }],
  request: { query: GetHoroscopeQuerySchema },
  responses: {
    200: {
      description: 'Horoscope for the requested period',
      content: { 'application/json': { schema: HoroscopeSchema } },
    },
    404: errorResponse('No horoscope available for today yet'),
    401: errorResponse('Unauthorized'),
  },
});

horoscopeRouter.openapi(getHoroscopeRoute, async (c) => {
  const user = c.get('user');
  const { period } = c.req.valid('query');

  if (period !== 'daily') {
    const row = await getOrGenerateHoroscope(user, period);
    return c.json(toHoroscopeDto(row), 200);
  }

  const row = await getHoroscopeForUser(user.id);
  if (!row) {
    return c.json(
      {
        error: {
          code: 'NOT_FOUND',
          message: 'No horoscope available for today yet. Please check back shortly.',
        },
      },
      404,
    );
  }
  return c.json(toHoroscopeDto(row), 200);
});
