import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabase } from '@/lib/supabase/server';
import { renderToBuffer } from '@react-pdf/renderer';
import React from 'react';
import { Document, Page, Text, View, Image, StyleSheet, Font } from '@react-pdf/renderer';

export const dynamic = 'force-dynamic';

// Register a fallback font (uses built-in Helvetica)
const styles = StyleSheet.create({
  page:       { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header:     { flexDirection: 'row', alignItems: 'center', marginBottom: 20, paddingBottom: 12, borderBottom: '1px solid #e5e7eb' },
  logo:       { width: 48, height: 48, marginRight: 12, borderRadius: 6 },
  brandName:  { fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#1f2937' },
  tagline:    { fontSize: 10, color: '#6b7280', marginTop: 2 },
  title:      { fontSize: 22, fontFamily: 'Helvetica-Bold', marginBottom: 6 },
  subtitle:   { fontSize: 11, color: '#6b7280', marginBottom: 20 },
  section:    { marginBottom: 16 },
  sectionTitle:{ fontSize: 13, fontFamily: 'Helvetica-Bold', marginBottom: 6, paddingBottom: 4, borderBottom: '0.5px solid #e5e7eb' },
  row:        { flexDirection: 'row', marginBottom: 4 },
  label:      { fontSize: 9, color: '#9ca3af', width: 100 },
  value:      { fontSize: 9, color: '#374151', flex: 1 },
  body:       { fontSize: 10, color: '#374151', lineHeight: 1.6, marginBottom: 8 },
  footer:     { position: 'absolute', bottom: 30, left: 40, right: 40, borderTop: '0.5px solid #e5e7eb', paddingTop: 8, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8, color: '#9ca3af' },
  accent:     { color: '#7c3aed' },
  badge:      { backgroundColor: '#f3e8ff', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2, marginRight: 4, marginBottom: 4 },
  badgeText:  { fontSize: 8, color: '#7c3aed' },
});

function ReportPdf({
  reportType,
  client,
  branding,
  content,
}: {
  reportType: string;
  client: Record<string, string | null>;
  branding: Record<string, string | null>;
  content: string;
}) {
  const accentColor = branding.primary_color ?? '#7c3aed';
  return (
    React.createElement(Document, null,
      React.createElement(Page, { size: 'A4', style: styles.page },
        // Header
        React.createElement(View, { style: styles.header },
          branding.logo_url
            ? React.createElement(Image, { src: branding.logo_url, style: styles.logo })
            : React.createElement(View, { style: { ...styles.logo, backgroundColor: accentColor, justifyContent: 'center', alignItems: 'center' } },
                React.createElement(Text, { style: { color: '#fff', fontSize: 20 } }, '🔮')
              ),
          React.createElement(View, null,
            React.createElement(Text, { style: { ...styles.brandName, color: accentColor } }, branding.brand_name ?? 'Astrologer Portal'),
            branding.tagline ? React.createElement(Text, { style: styles.tagline }, branding.tagline) : null,
          )
        ),
        // Report title
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: { ...styles.title, color: accentColor } }, `${REPORT_TITLES[reportType] ?? reportType} Report`),
          React.createElement(Text, { style: styles.subtitle }, `Prepared for: ${client.name ?? 'Client'}`),
        ),
        // Client info
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, 'Birth Details'),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.label }, 'Name'), React.createElement(Text, { style: styles.value }, client.name ?? '—')),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.label }, 'Date of Birth'), React.createElement(Text, { style: styles.value }, client.dob ?? '—')),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.label }, 'Time of Birth'), React.createElement(Text, { style: styles.value }, client.birth_time ?? '—')),
          React.createElement(View, { style: styles.row }, React.createElement(Text, { style: styles.label }, 'Place of Birth'), React.createElement(Text, { style: styles.value }, client.birth_place ?? '—')),
        ),
        // Content
        React.createElement(View, { style: styles.section },
          React.createElement(Text, { style: styles.sectionTitle }, 'Analysis'),
          React.createElement(Text, { style: styles.body }, content),
        ),
        // Footer
        React.createElement(View, { style: styles.footer, fixed: true },
          React.createElement(Text, { style: styles.footerText }, branding.pdf_footer ?? `Generated by ${branding.brand_name ?? 'Astrologer Portal'}`),
          React.createElement(Text, { style: styles.footerText }, new Date().toLocaleDateString('en-IN')),
        )
      )
    )
  );
}

const REPORT_TITLES: Record<string, string> = {
  dosha:         'Dosha Analysis',
  manorajna:     'Manorajna (Personality)',
  compatibility: 'Compatibility',
};

const REPORT_CONTENT: Record<string, (client: Record<string, string | null>) => string> = {
  dosha: (c) => `This report analyses the key doshas (planetary afflictions) in ${c.name ?? "the client"}'s birth chart and provides remedial measures to mitigate their effects.

Based on the planetary positions at the time of birth, the following areas require attention. Mangal Dosha, if present, influences relationships and marriage timing. Kaal Sarp Dosha, formed when all planets are between Rahu and Ketu, creates karmic patterns that shape life circumstances. Pitra Dosha reflects ancestral karma requiring specific rituals.

Each dosha carries its own remedy — mantras, gemstones, charitable acts, and rituals performed at specific times can significantly reduce their impact. The astrologer will discuss specific recommendations based on the full chart analysis.

Note: This report is a general overview. For a complete and personalized analysis, consult with your astrologer to review the full birth chart in detail.`,

  manorajna: (c) => `The Manorajna (Joy of Mind) report reveals ${c.name ?? "the client"}'s core personality, emotional nature, and life's deeper purpose as seen through the lens of Vedic Jyotish.

The ascendant (Lagna) and its lord paint the outer personality — the face you show the world. The Moon sign reveals the inner emotional world, hidden from most people. The Sun sign shows the soul's true purpose in this lifetime.

Key personality strengths emerge from the planetary configurations at birth. Some planets bless the native with creative intelligence, others with emotional wisdom, physical strength, or spiritual sensitivity. Understanding these energies allows one to work with them rather than against them.

Life themes that recur — certain types of relationships, career patterns, emotional reactions — can all be traced to specific planetary placements and dashas. Awareness of these patterns is the first step toward conscious evolution.`,

  compatibility: (c) => `The Compatibility report analyses the planetary resonance between two individuals across key life areas: emotional harmony, physical attraction, intellectual compatibility, financial alignment, and spiritual connection.

Vedic compatibility (Ashtakoot Guna Milan) evaluates eight factors: Varna, Vashya, Tara, Yoni, Graha Maitri, Gana, Bhakut, and Nadi. Each carries specific weight. A score of 18+ out of 36 indicates good compatibility; 27+ indicates excellent harmony.

Beyond the numeric score, the chart comparison reveals the deeper karmic contract between two souls. Long-term success depends not just on planetary positions but on how each person responds to the energies the other brings into their life.

This report should be used as a guide for self-awareness and mutual understanding, not as a definitive verdict on a relationship's future.`,
};

export async function POST(req: NextRequest) {
  const supabase = await createServerSupabase();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const { report_type, customer_id } = await req.json() as { report_type: string; customer_id: string };

  if (!report_type || !customer_id) {
    return NextResponse.json({ error: 'report_type and customer_id required' }, { status: 400 });
  }

  const [{ data: client }, { data: brandingRow }] = await Promise.all([
    supabase
      .from('astrologer_customers')
      .select('name, dob, birth_time, birth_place')
      .eq('id', customer_id)
      .eq('astrologer_id', user.id)
      .maybeSingle(),
    supabase
      .from('astrologer_branding')
      .select('brand_name, logo_url, tagline, primary_color, pdf_footer')
      .eq('astrologer_id', user.id)
      .maybeSingle(),
  ]);

  if (!client) return NextResponse.json({ error: 'Client not found' }, { status: 404 });

  const clientData: Record<string, string | null> = {
    name:        client.name ?? null,
    dob:         client.dob  ?? null,
    birth_time:  (client as Record<string, unknown>).birth_time as string | null ?? null,
    birth_place: (client as Record<string, unknown>).birth_place as string | null ?? null,
  };

  const branding: Record<string, string | null> = {
    brand_name:    brandingRow?.brand_name    ?? null,
    logo_url:      brandingRow?.logo_url      ?? null,
    tagline:       brandingRow?.tagline       ?? null,
    primary_color: brandingRow?.primary_color ?? null,
    pdf_footer:    brandingRow?.pdf_footer    ?? null,
  };

  const contentFn = REPORT_CONTENT[report_type];
  if (!contentFn) return NextResponse.json({ error: 'Unknown report type' }, { status: 400 });

  const content = contentFn(clientData);

  const docElement = React.createElement(ReportPdf, { reportType: report_type, client: clientData, branding, content });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const pdfBuffer = await renderToBuffer(docElement as any);

  return new NextResponse(pdfBuffer as unknown as BodyInit, {
    headers: {
      'Content-Type':        'application/pdf',
      'Content-Disposition': `attachment; filename="${report_type}-report-${clientData.name?.replace(/\s+/g, '-') ?? 'client'}.pdf"`,
    },
  });
}
