-- ============================================================================
-- 002: Generated Reports + Neural Pathways
-- ============================================================================

-- ============================================================================
-- Fix trigger: handle empty string from Google OAuth metadata
-- ============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.users (id, email, name, credits)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(
            NULLIF(TRIM(NEW.raw_user_meta_data ->> 'full_name'), ''),
            NULLIF(TRIM(NEW.raw_user_meta_data ->> 'name'), ''),
            ''
        ),
        2
    )
    ON CONFLICT (id) DO UPDATE
        SET
            email = EXCLUDED.email,
            name = CASE
                WHEN (users.name IS NULL OR TRIM(users.name) = '')
                    THEN EXCLUDED.name
                ELSE users.name
            END;

    -- Credit transaction only for fresh inserts
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO public.credit_transactions (user_id, amount, type, description)
        VALUES (NEW.id, 2, 'signup_bonus', 'Welcome bonus credits')
        ON CONFLICT DO NOTHING;
    END IF;

    RETURN NEW;
END;
$$;

-- Re-attach the trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- GENERATED REPORTS — stores every report generated by a user
-- ============================================================================
CREATE TABLE IF NOT EXISTS generated_reports (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    report_type     text NOT NULL CHECK (report_type IN ('numerology', 'kundli_basic', 'kundli_standard', 'kundli_premium')),
    subject_name    text NOT NULL,
    subject_dob     text,
    subject_gender  text,
    profile_id      uuid REFERENCES birth_profiles(id) ON DELETE SET NULL,
    -- Computed numbers / metadata (lightweight, always stored)
    metadata        jsonb,
    -- Full AI-generated content (for re-download without re-running AI)
    ai_content      jsonb,
    -- Optional: filename that was sent to client
    pdf_filename    text,
    neural_pathway_id uuid,
    created_at      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_generated_reports_user_id    ON generated_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_generated_reports_created_at ON generated_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_generated_reports_subject    ON generated_reports(user_id, subject_name, subject_dob);

ALTER TABLE generated_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "generated_reports_select" ON generated_reports
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "generated_reports_insert" ON generated_reports
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "generated_reports_delete" ON generated_reports
    FOR DELETE USING (auth.uid() = user_id);

-- ============================================================================
-- NEURAL PATHWAYS — contextual profiles built over time for each subject
-- ============================================================================
CREATE TABLE IF NOT EXISTS neural_pathways (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- Subject identity (used to match across reports)
    subject_name        text NOT NULL,
    subject_dob         text,
    subject_gender      text,
    -- Relationship context
    relationship        text CHECK (relationship IN (
        'self', 'spouse', 'child', 'parent', 'sibling',
        'friend', 'colleague', 'client', 'other'
    )),
    -- Life context collected via post-generation questions
    life_goals          text[],
    current_challenges  text[],
    career_profession   text,
    health_notes        text,
    personality_notes   text,
    additional_context  jsonb,
    -- Linked report IDs (updated when new reports are saved)
    report_ids          uuid[],
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    -- One pathway per (user, subject_name, subject_dob) triplet
    UNIQUE (user_id, subject_name, subject_dob)
);

CREATE INDEX IF NOT EXISTS idx_neural_pathways_user_id ON neural_pathways(user_id);
CREATE INDEX IF NOT EXISTS idx_neural_pathways_subject ON neural_pathways(user_id, subject_name, subject_dob);

ALTER TABLE neural_pathways ENABLE ROW LEVEL SECURITY;

CREATE POLICY "neural_pathways_select" ON neural_pathways
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "neural_pathways_insert" ON neural_pathways
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "neural_pathways_update" ON neural_pathways
    FOR UPDATE USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "neural_pathways_delete" ON neural_pathways
    FOR DELETE USING (auth.uid() = user_id);

-- ============================================================================
-- Helper: auto-update updated_at on neural_pathways
-- ============================================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS neural_pathways_updated_at ON neural_pathways;
CREATE TRIGGER neural_pathways_updated_at
    BEFORE UPDATE ON neural_pathways
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
