-- ── Pandit & Puja feature ────────────────────────────────────────────────────
-- Tables: pujas (catalog) + pandits (directory, 10 cities)
-- All data world-readable; only service-role / admin can mutate.
-- Seed data sourced from migrations/1.json (delete that file after applying).

create table if not exists pujas (
  id              uuid        primary key default gen_random_uuid(),
  slug            text        unique not null,
  name_en         text        not null,
  name_sanskrit   text        not null,
  short_desc      text        not null,
  long_desc       text        not null,
  deity           text        not null,
  image_path      text        not null default '',  -- object path within 'pujas' Supabase Storage bucket
  primary_dosha   text,                              -- 'mangal'|'kaalsarp'|'sadesati'|'pitra'|'kemdruma'|'grahan'|'guruchandal'
  primary_planet  text,                              -- 'sun'|'moon'|'mars'|'mercury'|'jupiter'|'venus'|'saturn'|'rahu'|'ketu'
  intent_tags     text[]      not null default '{}',
  base_priority   int         not null default 5,
  duration_min    int,
  created_at      timestamptz not null default now()
);

create table if not exists pandits (
  id               uuid        primary key default gen_random_uuid(),
  name             text        not null,
  photo_url        text,
  city             text        not null,  -- slug: 'delhi'|'mumbai'|'bengaluru'|'chennai'|'hyderabad'|'kolkata'|'pune'|'ahmedabad'|'varanasi'|'prayagraj'
  phone            text        not null,
  whatsapp         text,
  years_experience int,
  languages        text[]      not null default '{}',
  specialisations  text[]      not null default '{}',  -- references pujas.slug values
  rating           numeric(2,1),
  verified         bool        not null default false,
  created_at       timestamptz not null default now()
);

create index if not exists pandits_city_idx on pandits(city);

alter table pujas   enable row level security;
alter table pandits enable row level security;

drop policy if exists "pujas_read_all"   on pujas;
drop policy if exists "pandits_read_all" on pandits;

create policy "pujas_read_all"   on pujas   for select using (true);
create policy "pandits_read_all" on pandits for select using (true);

-- ── Puja seed data ────────────────────────────────────────────────────────────

insert into pujas (slug, name_en, name_sanskrit, short_desc, long_desc, deity, primary_dosha, primary_planet, intent_tags, base_priority, duration_min) values
('ganapathi-homam',      'Ganapathi Homam',               'गणपति होमम्',            'Remove obstacles and invite auspicious beginnings.',                        'Ganapathi Homam is performed to seek blessings of Lord Ganesha before any important venture. The fire ritual clears obstacles and bestows wisdom, success, and divine grace upon the worshipper and their family.',                                                                                                    'Ganesha',                null,        null,       array['obstacles','career','wealth','education'],             65, 90),
('navagraha-shanti',     'Navagraha Shanti Homam',        'नवग्रह शान्ति होमम्',    'Pacify all nine planets to restore cosmic balance.',                        'Navagraha Shanti is a comprehensive fire ritual that appeases all nine celestial bodies simultaneously. Ideal for those experiencing general difficulties across multiple life areas or when multiple graha doshas exist in the chart.',                                                                               'Navagrahas',             null,        null,       array['health','protection','wealth','career'],               70, 180),
('maha-mrityunjaya-jaap','Maha Mrityunjaya Jaap',         'महामृत्युञ्जय जप',       'Conquer illness and fear through Shiva''s grace.',                          'The Maha Mrityunjaya mantra repeated 1,25,000 times dissolves karmic debts related to health and longevity, strengthens Moon energy, and provides divine protection against untimely misfortune.',                                                                                                                  'Shiva',                  null,        'moon',     array['health','longevity','protection'],                     60, 240),
('rudra-abhishek',       'Rudra Abhishek',                'रुद्राभिषेक',             'Sacred bathing of Shivalinga to cleanse karma.',                            'Rudra Abhishek involves ceremonial bathing of the Shivalinga with milk, honey, ghee, and sacred water while chanting the Sri Rudram. It purifies negative karma and brings peace to home and family.',                                                                                                                     'Shiva',                  null,        null,       array['health','protection','marriage','home'],               55, 120),
('mangal-shanti',        'Mangal Shanti Puja',            'मंगल शान्ति पूजा',       'Remedy Mangal Dosha and soften Mars afflictions.',                          'Mangal Shanti Puja pacifies planet Mars and nullifies Mangal Dosha. Strongly recommended before marriage when Mangal Dosha is detected, reducing delay in marriage, marital discord, and health issues.',                                                                                                               'Mangal (Mars)',           'mangal',    'mars',     array['marriage','health','protection'],                      80, 150),
('kaal-sarp-shanti',     'Kaal Sarp Shanti Puja',         'काल सर्प शान्ति पूजा',   'Release the serpent axis grip of Rahu-Ketu on your life.',                  'When all seven planets fall between Rahu and Ketu, Kaal Sarp Dosha forms. This powerful puja dissolves repeated failures, delays, and obstacles — and opens pathways to success.',                                                                                                                                   'Shiva / Nagdevata',      'kaalsarp',  'rahu',     array['career','protection','wealth','marriage'],             80, 240),
('sade-sati-shanti',     'Sade Sati / Shani Shanti Puja', 'साढ़े साती शान्ति पूजा', 'Ease Saturn''s 7.5-year trial and transform hardship into growth.',          'Sade Sati occurs when Saturn transits the Moon''s sign and the adjacent signs for 7.5 years. This puja pacifies Lord Shani, reduces losses and delays, and channels Saturn''s energy toward discipline and wisdom.',                                                                                                  'Shani (Saturn)',          'sadesati',  'saturn',   array['career','health','protection','wealth'],               80, 150),
('pitra-tarpan',         'Pitra Tarpan & Shraadh',        'पितृ तर्पण श्राद्ध',     'Offer water and gratitude to release ancestral debts.',                     'Pitra Tarpan is a sacred water offering ritual for deceased ancestors. Performed on Amavasya or Pitrupaksha, it satisfies the Pitrus, releases ancestral karma, and brings peace and prosperity to the family.',                                                                                                         'Pitru Devtas',           'pitra',     'sun',      array['moksha','protection','health'],                        70, 90),
('pitra-dosh-nivaran',   'Pitra Dosh Nivaran Puja',       'पितृ दोष निवारण पूजा',   'Comprehensive puja to fully remedy Pitra Dosha in your chart.',             'A full Pitra Dosh Nivaran puja includes Vishnu Puja, Brahmin bhojan, and specific mantras to appease the Sun and ancestors. Recommended when Pitra Dosha is detected with moderate to severe intensity.',                                                                                                          'Pitru Devtas / Vishnu',  'pitra',     'sun',      array['moksha','health','wealth','protection'],                75, 180),
('maha-lakshmi-puja',    'Maha Lakshmi Puja',             'महालक्ष्मी पूजा',         'Invite abundance and the blessings of the Goddess of Wealth.',              'Maha Lakshmi Puja attracts material prosperity, overcomes financial difficulties, and strengthens Venus in the chart. Beneficial for those in business, facing monetary stagnation, or seeking marital harmony.',                                                                                                   'Lakshmi',                null,        'venus',    array['wealth','marriage','home'],                            50, 90),
('saraswati-puja',       'Saraswati Puja',                'सरस्वती पूजा',            'Awaken intelligence, speech, and artistic mastery.',                        'Saraswati Puja strengthens Mercury in the chart, helps students excel, improves communication and creative expression. Ideal for those in education, writing, music, or teaching.',                                                                                                                                        'Saraswati',              null,        'mercury',  array['education','career','obstacles'],                      45, 60),
('durga-saptashati',     'Durga Saptashati Path',         'दुर्गा सप्तशती पाठ',     '700 verses of divine feminine power for protection and victory.',           'The Durga Saptashati is a recitation of 700 shlokas describing Goddess Durga''s victory over evil. Performed for protection from enemies, overcoming serious obstacles, and invoking the divine feminine.',                                                                                                             'Durga',                  null,        null,       array['protection','health','obstacles','career'],            55, 180),
('sudarshana-homam',     'Sudarshana Homam',              'सुदर्शन होमम्',           'Invoke Vishnu''s divine disc to destroy negative forces.',                  'Sudarshana Homam is a powerful fire ritual invoking Lord Vishnu''s Sudarshana Chakra. It protects from evil eye, black magic, and enemies, and strengthens the Sun for those in authority roles.',                                                                                                              'Vishnu / Sudarshana',    null,        'sun',      array['protection','health','career'],                        50, 150),
('chandi-homam',         'Chandi Homam',                  'चण्डी होमम्',             'An intensive fire ritual to the fierce goddess Chandi.',                    'Chandi Homam involves 64 types of offerings and is one of the most powerful fire rituals in the Vedic tradition. Performed to overcome grave difficulties, break karmic cycles, and invoke divine intervention.',                                                                                                        'Chandi (Durga)',         null,        null,       array['protection','wealth','obstacles','health'],            55, 300),
('ayushya-homam',        'Ayushya Homam',                 'आयुष्य होमम्',            'A life-extending ritual for health, longevity, and safe childbirth.',      'Ayushya Homam is dedicated to Lord Shiva and the presiding deity of longevity. Performed on birthdays or before childbirth, it is also recommended for those with weak Moon or recurring health challenges.',                                                                                                      'Shiva / Ayushya Devata', null,        'moon',     array['health','longevity','childbirth'],                     50, 120),
('vastu-shanti',         'Vastu Shanti Puja',             'वास्तु शान्ति पूजा',     'Harmonise your home or workspace with the five elements.',                  'Vastu Shanti Puja is performed before or after moving into a new space to purify Vastu defects, appease directional deities, correct elemental imbalances, and ensure peace and prosperity for inhabitants.',                                                                                                    'Vastu Purusha',          null,        null,       array['home','property','protection'],                        50, 120),
('griha-pravesh',        'Griha Pravesh Puja',            'गृहप्रवेश पूजा',          'Consecrate your new home with Vedic rites before the first entry.',        'Griha Pravesh is the sacred housewarming ceremony performed on an auspicious muhurta. It involves Vastu puja, Ganapathi puja, havan, and sprinkling of holy water, filling the home with divine blessings.',                                                                                                     'All deities',            null,        null,       array['home','property','protection'],                        45, 150),
('surya-aradhana',       'Surya Aradhana',                'सूर्य आराधना',            'Worship the Sun god for authority, health, and career success.',            'Surya Aradhana strengthens the Sun through water offerings, Aditya Hridayam recitation, and Sun mantras. Beneficial for leaders, government employees, and those with weak Sun facing issues with authority.',                                                                                                        'Surya',                  null,        'sun',      array['career','health','education'],                         45, 60),
('chandra-shanti',       'Chandra Shanti Puja',           'चन्द्र शान्ति पूजा',     'Calm the mind and nourish the Moon for emotional well-being.',              'Chandra Shanti Puja strengthens the Moon in the birth chart. A weak Moon causes emotional instability, depression, poor memory, and relationship difficulties. White flowers and silver items are offered to Lord Chandra.',                                                                                       'Chandra (Moon)',         null,        'moon',     array['health','marriage','protection'],                      45, 90),
('budha-shanti',         'Budha Graha Shanti',            'बुध ग्रह शान्ति',         'Strengthen Mercury for clear thinking, speech, and commerce.',              'Budha Shanti puja pacifies and strengthens Mercury. Ideal for students, writers, traders, and those in communication roles experiencing confusion, speech difficulties, or poor academic performance.',                                                                                                                'Budha (Mercury)',        null,        'mercury',  array['education','career','wealth'],                         45, 90),
('guru-puja',            'Brihaspati / Guru Puja',        'बृहस्पति गुरु पूजा',     'Invoke Jupiter''s wisdom, grace, and divine knowledge.',                    'Guru Puja strengthens the most benefic planet in Vedic astrology. A strong Jupiter brings children, marital happiness, wisdom, and wealth. Recommended for those with delays in marriage, childlessness, or financial stagnation.',                                                                                 'Brihaspati (Jupiter)',   null,        'jupiter',  array['wealth','education','marriage','childbirth'],          45, 90),
('shukra-puja',          'Shukra Graha Puja',             'शुक्र ग्रह पूजा',         'Attract love, beauty, and material luxury through Venus worship.',          'Shukra Puja enhances Venus in the birth chart. A strong Venus brings marital bliss, creative success, artistic talents, and material comforts. Beneficial for relationship difficulties caused by a weak Venus.',                                                                                                   'Shukra (Venus)',         null,        'venus',    array['marriage','wealth','career'],                          45, 90),
('rahu-shanti',          'Rahu Graha Shanti',             'राहु ग्रह शान्ति',         'Pacify the shadow planet Rahu for clarity and karmic relief.',              'Rahu Shanti puja mitigates the malefic effects of Rahu — confusion, addiction, sudden reversals. Rahu-specific mantras, incense, and black sesame offerings bring clarity, stability, and relief from chaotic Rahu energy.',                                                                                    'Rahu',                   null,        'rahu',     array['career','protection','health'],                        50, 120),
('ketu-shanti',          'Ketu Graha Shanti',             'केतु ग्रह शान्ति',         'Quieten Ketu''s detachment for spiritual peace and grounding.',             'Ketu Shanti puja calms the influence of Ketu, the south node of the Moon. An afflicted Ketu causes mysterious illnesses and unexplained losses. This puja helps ground spiritual energy and support moksha.',                                                                                                   'Ketu',                   null,        'ketu',     array['moksha','protection','health'],                        50, 120),
('hanuman-puja',         'Hanuman Puja & Chalisa',        'हनुमान पूजा',             'Call on Hanuman''s strength for courage and protection from evil.',         'Hanuman Puja with Chalisa recitation is among the most popular Vedic remedies. Hanuman is the deity of Mars energy — strength, courage, and devotion. This puja removes fear, wards off evil eye, and is recommended on Tuesdays.',                                                                                   'Hanuman',                null,        'mars',     array['protection','health','obstacles','career'],            55, 60),
('satya-narayan-katha',  'Satya Narayan Katha',           'सत्यनारायण कथा',         'A beloved Vishnu puja for family harmony and fulfilling wishes.',           'Satya Narayan Katha is traditionally performed on Purnima to express gratitude and seek Lord Vishnu''s blessings for family well-being, fulfilment of desires, success in ventures, and as thanksgiving for boons received.',                                                                                    'Satya Narayan (Vishnu)', null,        null,       array['wealth','home','protection','health'],                 50, 120),
('vishnu-sahasranama',   'Vishnu Sahasranama Path',       'विष्णु सहस्रनाम पाठ',    'Chant 1000 names of Lord Vishnu for cosmic protection and moksha.',         'The Vishnu Sahasranama is a sequence of 1000 names of Lord Vishnu from the Mahabharata. Regular recitation protects from all fears, removes sins, and bestows health, wealth, and liberation.',                                                                                                          'Vishnu',                 null,        null,       array['protection','moksha','health'],                        50, 90),
('grahan-dosh-nivaran',  'Grahan Dosh Nivaran Puja',      'ग्रहण दोष निवारण पूजा', 'Remedy eclipse-related doshas that affect health and clarity.',              'Grahan Dosha occurs when the Sun or Moon is conjunct Rahu or Ketu in the birth chart, causing confusion and health issues. This puja performs specific mantras for both the eclipsed luminary and the shadow planets.',                                                                                      'Surya / Chandra / Rahu-Ketu','grahan',null,       array['health','protection','career'],                        75, 150),
('guru-chandal-shanti',  'Guru Chandal Dosh Shanti',      'गुरु चाण्डाल दोष शान्ति','Purify Jupiter when afflicted by Rahu for wisdom and ethics.',              'Guru Chandal Dosha forms when Jupiter is conjunct or aspected by Rahu, causing poor judgment and difficulties with teachers. This puja performs Guru Puja and Rahu Shanti together to restore Jupiter''s purity.',                                                                                          'Brihaspati / Rahu',     'guruchandal','jupiter',  array['education','career','protection','wealth'],            75, 180),
('kemdruma-shanti',      'Kemdruma Dosh Nivaran',         'केमद्रुम दोष निवारण',    'Remedy the isolated Moon dosha for emotional security.',                    'Kemdruma Dosha arises when the Moon has no planet in adjacent houses, leaving it isolated and weakened. This causes emotional insecurity and relationship difficulties. White flowers, pearl offerings, and Chandra mantras restore the Moon.',                                                                  'Chandra (Moon)',         'kemdruma',  'moon',     array['health','marriage','protection'],                      75, 120),
('mahalakshmi-yagna',    'Maha Lakshmi Yagna',            'महालक्ष्मी यज्ञ',         'An intensive prosperity fire ritual with 64 types of offerings.',           'Maha Lakshmi Yagna is a large-scale fire ritual with 64 types of offerings including rare herbs, lotus flowers, ghee, and saffron. Performed with multiple priests, it powerfully activates Venus, removes financial blockages, and invites lasting prosperity.',                                          'Maha Lakshmi',           null,        'venus',    array['wealth','career','home'],                              55, 360)
on conflict (slug) do update set
  name_en = excluded.name_en, name_sanskrit = excluded.name_sanskrit,
  short_desc = excluded.short_desc, long_desc = excluded.long_desc,
  deity = excluded.deity, primary_dosha = excluded.primary_dosha,
  primary_planet = excluded.primary_planet, intent_tags = excluded.intent_tags,
  base_priority = excluded.base_priority, duration_min = excluded.duration_min;

-- ── Pandit seed data (10 cities × 10 pandits) ────────────────────────────────
-- NOTE: Phone numbers are placeholders — update with real contacts before launch.

insert into pandits (name, city, phone, whatsapp, years_experience, languages, specialisations, rating, verified) values
-- Delhi
('Pandit Manish Jha',             'delhi',     '+919811001001', '+919811001001', 20, array['Hindi','Sanskrit'],           array['navagraha-shanti','mangal-shanti','rudra-abhishek'],         4.9, true),
('Yogdasha Jyotish Kendra',       'delhi',     '+919811001002', '+919811001002', 25, array['Hindi','Sanskrit','English'], array['kaal-sarp-shanti','sade-sati-shanti','grahan-dosh-nivaran'], 5.0, true),
('Pandit Joy Bhattacharya',       'delhi',     '+919811001003', null,            18, array['Hindi','Bengali','Sanskrit'], array['durga-saptashati','pitra-tarpan','chandi-homam'],            4.9, true),
('Guru Pasha Ji',                 'delhi',     '+919811001004', '+919811001004', 30, array['Hindi','Sanskrit'],           array['guru-puja','guru-chandal-shanti','vishnu-sahasranama'],       4.9, true),
('Pandit Naveen Shastri',         'delhi',     '+919811001005', '+919811001005', 15, array['Hindi','Sanskrit'],           array['satya-narayan-katha','hanuman-puja','ganapathi-homam'],      4.8, false),
('Pt. Devendra Sharma',           'delhi',     '+919811001006', null,            22, array['Hindi','Sanskrit'],           array['vastu-shanti','griha-pravesh','ganapathi-homam'],            4.7, true),
('Acharya Pankaj',                'delhi',     '+919811001007', '+919811001007', 28, array['Hindi','Sanskrit','English'], array['vastu-shanti','griha-pravesh','navagraha-shanti'],           5.0, true),
('Pandit Krishan Kant',           'delhi',     '+919811001008', '+919811001008', 20, array['Hindi','Sanskrit'],           array['kemdruma-shanti','chandra-shanti','maha-mrityunjaya-jaap'],  4.9, true),
('Shri Ram Poojan Kendra',        'delhi',     '+919811001009', null,            35, array['Hindi','Sanskrit'],           array['pitra-tarpan','pitra-dosh-nivaran','surya-aradhana'],        4.5, true),
('Arya Samaj Mandir Trust',       'delhi',     '+919811001010', '+919811001010', 40, array['Hindi','Sanskrit'],           array['griha-pravesh','mangal-shanti','satya-narayan-katha'],       4.4, true),
-- Mumbai
('Swami Suyash Jangam',           'mumbai',    '+919221001001', '+919221001001', 20, array['Marathi','Hindi','Sanskrit'], array['vastu-shanti','griha-pravesh','ganapathi-homam'],            5.0, true),
('Pandit Sunil Balkrishna Joshi', 'mumbai',    '+919221001002', '+919221001002', 25, array['Marathi','Hindi','Sanskrit'], array['navagraha-shanti','satya-narayan-katha','mangal-shanti'],   5.0, true),
('Vedicc Jyotish',                'mumbai',    '+919221001003', '+919221001003', 18, array['Hindi','Sanskrit','English'], array['kaal-sarp-shanti','grahan-dosh-nivaran','rahu-shanti'],      5.0, true),
('Pandit Vikram Sharma',          'mumbai',    '+919221001004', null,            15, array['Hindi','Sanskrit'],           array['vastu-shanti','griha-pravesh','satya-narayan-katha'],        4.3, false),
('Pandit R.K. Shastri',           'mumbai',    '+919221001005', '+919221001005', 30, array['Hindi','Sanskrit','Marathi'], array['mangal-shanti','kaal-sarp-shanti','maha-mrityunjaya-jaap'],  4.8, true),
('Pandit Durga Prasad',           'mumbai',    '+919221001006', '+919221001006', 22, array['Marathi','Hindi','Sanskrit'], array['pitra-tarpan','pitra-dosh-nivaran','durga-saptashati'],      5.0, true),
('Ganesh Maharaj',                'mumbai',    '+919221001007', null,            28, array['Marathi','Hindi'],            array['ganapathi-homam','satya-narayan-katha','vastu-shanti'],      4.7, true),
('Pandit Rahul Sanat',            'mumbai',    '+919221001008', '+919221001008', 14, array['Hindi','Sanskrit','English'], array['navagraha-shanti','sade-sati-shanti','surya-aradhana'],      4.9, true),
('Acharya Vinay',                 'mumbai',    '+919221001009', '+919221001009', 12, array['Hindi','Marathi','Sanskrit'], array['vishnu-sahasranama','rudra-abhishek','maha-mrityunjaya-jaap'],4.6, false),
('Bhagypad Astro',                'mumbai',    '+919221001010', '+919221001010', 35, array['Marathi','Hindi','Sanskrit'], array['guru-chandal-shanti','kemdruma-shanti','chandra-shanti'],    5.0, true),
-- Bengaluru
('Sri Sai Krishna Jhothishylaya', 'bengaluru', '+918001001001', '+918001001001', 20, array['Kannada','Tamil','Sanskrit'], array['navagraha-shanti','surya-aradhana','budha-shanti'],          4.9, true),
('Shri Suryanarayana Vedic Centre','bengaluru','+918001001002', null,            25, array['Kannada','Sanskrit','English'],array['vastu-shanti','griha-pravesh','ganapathi-homam'],            4.9, true),
('Tamil Iyer Bangalore',          'bengaluru', '+918001001003', '+918001001003', 30, array['Tamil','Sanskrit','Kannada'], array['mangal-shanti','kaal-sarp-shanti','navagraha-shanti'],       4.9, true),
('Sri Guru Sanatana Astro Centre','bengaluru', '+918001001004', '+918001001004', 35, array['Kannada','Sanskrit'],         array['guru-puja','guru-chandal-shanti','vishnu-sahasranama'],       5.0, true),
('Pandit Sridhar',                'bengaluru', '+918001001005', null,            18, array['Kannada','Hindi','Sanskrit'], array['rudra-abhishek','maha-mrityunjaya-jaap','sade-sati-shanti'], 4.9, true),
('Shri Sumukha Purohits',         'bengaluru', '+918001001006', '+918001001006', 22, array['Kannada','Sanskrit'],         array['satya-narayan-katha','griha-pravesh','pitra-tarpan'],        5.0, true),
('Pandit Akash Ji',               'bengaluru', '+918001001007', '+918001001007', 15, array['Hindi','Kannada','Sanskrit'], array['ganapathi-homam','hanuman-puja','vastu-shanti'],             5.0, false),
('Bharath Bhat Purohit',          'bengaluru', '+918001001008', null,            28, array['Kannada','Tulu','Sanskrit'],  array['rudra-abhishek','maha-lakshmi-puja','chandra-shanti'],       4.9, true),
('Pandit Raghvendra Dwivedi',     'bengaluru', '+918001001009', '+918001001009', 20, array['Kannada','Hindi','Sanskrit'], array['vastu-shanti','kaal-sarp-shanti','grahan-dosh-nivaran'],     5.0, true),
('Telugu Pujari Chaganti Pavan',  'bengaluru', '+918001001010', '+918001001010', 12, array['Telugu','Kannada','Sanskrit'],array['sudarshana-homam','vishnu-sahasranama','satya-narayan-katha'],5.0, true),
-- Chennai
('Sri Raghavendra Swamy Research Centre','chennai','+914401001001','+914401001001',40,array['Tamil','Sanskrit'],          array['navagraha-shanti','mangal-shanti','vishnu-sahasranama'],      5.0, true),
('Ganesan Iyer',                  'chennai',   '+914401001002', null,            25, array['Tamil','Sanskrit'],           array['vastu-shanti','griha-pravesh','ganapathi-homam'],            4.5, true),
('Pandit Deepak Awasthi',         'chennai',   '+914401001003', '+914401001003', 20, array['Hindi','Sanskrit','Tamil'],   array['mangal-shanti','kaal-sarp-shanti','sade-sati-shanti'],       4.9, true),
('Oruganti Vidya Sagar Sastry',   'chennai',   '+914401001004', '+914401001004', 35, array['Telugu','Tamil','Sanskrit'],  array['rudra-abhishek','maha-mrityunjaya-jaap','sudarshana-homam'], 4.9, true),
('Velavan Prohitham',             'chennai',   '+914401001005', '+914401001005', 30, array['Tamil','Sanskrit'],           array['satya-narayan-katha','pitra-tarpan','surya-aradhana'],       4.9, true),
('Bharat Waj Iyengar',            'chennai',   '+914401001006', null,            28, array['Tamil','Sanskrit','English'], array['durga-saptashati','chandi-homam','ganapathi-homam'],         4.9, true),
('Chandrasekar Shiva Iyer',       'chennai',   '+914401001007', '+914401001007', 22, array['Tamil','Sanskrit'],           array['mangal-shanti','ayushya-homam','chandra-shanti'],            4.7, false),
('Pandit A R Sundararajan',       'chennai',   '+914401001008', null,            18, array['Tamil','Sanskrit'],           array['grahan-dosh-nivaran','kemdruma-shanti','guru-puja'],         4.7, true),
('Sriram Sastrigal',              'chennai',   '+914401001009', '+914401001009', 45, array['Tamil','Sanskrit'],           array['vishnu-sahasranama','rudra-abhishek','kaal-sarp-shanti'],    4.9, true),
('Vignesh Pandit',                'chennai',   '+914401001010', '+914401001010', 12, array['Tamil','Hindi','English'],    array['ganapathi-homam','vastu-shanti','satya-narayan-katha'],      5.0, false),
-- Hyderabad
('North Indian Hindi Pandit',     'hyderabad', '+914001001001', '+914001001001', 20, array['Hindi','Sanskrit','Telugu'],  array['mangal-shanti','kaal-sarp-shanti','maha-mrityunjaya-jaap'],  4.8, true),
('Sri Chakra Bhavishyavaani',     'hyderabad', '+914001001002', '+914001001002', 25, array['Telugu','Sanskrit','English'],array['navagraha-shanti','grahan-dosh-nivaran','surya-aradhana'],  4.9, true),
('Pandit Rajnish Tiwari',         'hyderabad', '+914001001003', null,            18, array['Hindi','Sanskrit'],           array['vastu-shanti','griha-pravesh','ganapathi-homam'],            5.0, true),
('Sri Gayathri Pooja Pandit',     'hyderabad', '+914001001004', '+914001001004', 30, array['Telugu','Sanskrit'],          array['durga-saptashati','satya-narayan-katha','pitra-tarpan'],    4.7, true),
('Sri Umapathi Jyothishalayam',   'hyderabad', '+914001001005', '+914001001005', 35, array['Telugu','Sanskrit'],          array['kaal-sarp-shanti','sade-sati-shanti','rahu-shanti'],        4.9, true),
('Pandit Satyanarayana',          'hyderabad', '+914001001006', null,            22, array['Telugu','Hindi'],             array['satya-narayan-katha','griha-pravesh','hanuman-puja'],        4.6, false),
('Acharya Srinivas',              'hyderabad', '+914001001007', '+914001001007', 28, array['Telugu','Sanskrit','Kannada'],array['vishnu-sahasranama','sudarshana-homam','maha-lakshmi-puja'],4.8, true),
('Pandit Murali Krishna',         'hyderabad', '+914001001008', '+914001001008', 15, array['Telugu','Hindi','Sanskrit'],  array['ganapathi-homam','chandi-homam','navagraha-shanti'],        5.0, true),
('Sri Venkateshwara Puja Kendra', 'hyderabad', '+914001001009', null,            40, array['Telugu','Sanskrit'],          array['guru-chandal-shanti','pitra-dosh-nivaran','kemdruma-shanti'],4.4, true),
('Pt. Gajanan Krishna Maharaj',   'hyderabad', '+914001001010', '+914001001010', 32, array['Telugu','Marathi','Sanskrit'],array['rudra-abhishek','maha-mrityunjaya-jaap','ayushya-homam'],  4.8, true),
-- Kolkata
('Astrologer Samrat Bose',        'kolkata',   '+913301001001', '+913301001001', 30, array['Bengali','Hindi','Sanskrit'], array['navagraha-shanti','kaal-sarp-shanti','grahan-dosh-nivaran'],5.0, true),
('Pandit Sankha Mukharjee',       'kolkata',   '+913301001002', null,            25, array['Bengali','Sanskrit'],         array['satya-narayan-katha','vishnu-sahasranama','pitra-tarpan'], 5.0, true),
('Pandit Akhilesh Radhe Krishna Shastri','kolkata','+913301001003','+913301001003',35,array['Hindi','Bengali','Sanskrit'],array['mangal-shanti','sade-sati-shanti','maha-mrityunjaya-jaap'], 4.9, true),
('Pandit Shri Manish Ji Mishra',  'kolkata',   '+913301001004', '+913301001004', 20, array['Bengali','Hindi','Sanskrit'], array['griha-pravesh','vastu-shanti','ganapathi-homam'],           5.0, true),
('Tarak Bhattacharyya',           'kolkata',   '+913301001005', null,            28, array['Bengali','Sanskrit'],         array['durga-saptashati','chandi-homam','ketu-shanti'],             4.5, true),
('Sree Goutam Sastri',            'kolkata',   '+913301001006', '+913301001006', 22, array['Bengali','Sanskrit','English'],array['guru-puja','guru-chandal-shanti','budha-shanti'],           4.8, true),
('Pandit Biswajit',               'kolkata',   '+913301001007', '+913301001007', 15, array['Bengali','Hindi'],            array['mangal-shanti','satya-narayan-katha','hanuman-puja'],        4.7, false),
('Acharya Rajat',                 'kolkata',   '+913301001008', null,            18, array['Bengali','Sanskrit'],         array['griha-pravesh','vastu-shanti','surya-aradhana'],             4.9, true),
('Pandit Anupam',                 'kolkata',   '+913301001009', '+913301001009', 12, array['Bengali','Hindi','English'],  array['ayushya-homam','chandra-shanti','kemdruma-shanti'],          4.6, false),
('Shri Bhrigu Jyotish',           'kolkata',   '+913301001010', '+913301001010', 40, array['Bengali','Sanskrit'],         array['pitra-dosh-nivaran','rahu-shanti','navagraha-shanti'],       5.0, true),
-- Pune
('Pandit Vasudev Shastri',        'pune',      '+912001001001', '+912001001001', 25, array['Marathi','Hindi','Sanskrit'], array['navagraha-shanti','mangal-shanti','griha-pravesh'],          4.9, true),
('Pandit Surendra Shastri',       'pune',      '+912001001002', null,            20, array['Marathi','Hindi','Sanskrit'], array['kaal-sarp-shanti','sade-sati-shanti','maha-mrityunjaya-jaap'],4.9, true),
('Pandit Aditya Kulkarni',        'pune',      '+912001001003', '+912001001003', 30, array['Marathi','Sanskrit'],         array['ganapathi-homam','satya-narayan-katha','vastu-shanti'],     5.0, true),
('Utpat Guruji Pandharpurkar',    'pune',      '+912001001004', '+912001001004', 35, array['Marathi','Sanskrit'],         array['vishnu-sahasranama','sudarshana-homam','rudra-abhishek'],  4.8, true),
('Pandit Anant M Joshi Guruji',   'pune',      '+912001001005', null,            28, array['Marathi','Hindi'],            array['ganapathi-homam','chandi-homam','durga-saptashati'],        4.9, true),
('Acharya Deshpande',             'pune',      '+912001001006', '+912001001006', 22, array['Marathi','Sanskrit'],         array['guru-chandal-shanti','guru-puja','grahan-dosh-nivaran'],    4.7, true),
('Pt. Vinayak Kulkarni',          'pune',      '+912001001007', '+912001001007', 18, array['Marathi','Hindi','English'],  array['vastu-shanti','griha-pravesh','navagraha-shanti'],           4.8, false),
('Pandit Sandeep',                'pune',      '+912001001008', null,            15, array['Marathi','Hindi'],            array['mangal-shanti','maha-lakshmi-puja','satya-narayan-katha'],   4.9, false),
('Shri Sai Astro Pune',           'pune',      '+912001001009', '+912001001009', 12, array['Marathi','Hindi','English'],  array['pitra-tarpan','kemdruma-shanti','chandra-shanti'],           4.6, false),
('Pandit Mahesh Shastri',         'pune',      '+912001001010', '+912001001010', 32, array['Marathi','Sanskrit'],         array['ayushya-homam','pitra-dosh-nivaran','rahu-shanti'],          4.5, true),
-- Ahmedabad
('Shastri Nirav Joshi',           'ahmedabad', '+917901001001', '+917901001001', 25, array['Gujarati','Hindi','Sanskrit'],array['navagraha-shanti','mangal-shanti','ganapathi-homam'],        5.0, true),
('Pandit Kartik',                 'ahmedabad', '+917901001002', '+917901001002', 18, array['Gujarati','Hindi'],           array['satya-narayan-katha','griha-pravesh','vastu-shanti'],        4.9, true),
('Shree Vaman Jyotish',           'ahmedabad', '+917901001003', null,            30, array['Gujarati','Sanskrit'],        array['kaal-sarp-shanti','sade-sati-shanti','grahan-dosh-nivaran'],4.8, true),
('Rudraksh International',        'ahmedabad', '+917901001004', '+917901001004', 22, array['Gujarati','Hindi','Sanskrit'],array['maha-mrityunjaya-jaap','rudra-abhishek','kaal-sarp-shanti'],4.9, true),
('Pandit Dhyan Kumar',            'ahmedabad', '+917901001005', null,            20, array['Gujarati','Hindi'],           array['pitra-tarpan','pitra-dosh-nivaran','surya-aradhana'],        4.7, true),
('Acharya Trivedi',               'ahmedabad', '+917901001006', '+917901001006', 35, array['Gujarati','Sanskrit'],        array['guru-chandal-shanti','guru-puja','vishnu-sahasranama'],      4.9, true),
('Pandit Maulik Shastri',         'ahmedabad', '+917901001007', '+917901001007', 28, array['Gujarati','Hindi','Sanskrit'],array['vastu-shanti','griha-pravesh','ganapathi-homam'],            4.8, false),
('Shri Jaimini Jyotish',          'ahmedabad', '+917901001008', null,            15, array['Gujarati','Sanskrit'],        array['maha-lakshmi-puja','shukra-puja','mahalakshmi-yagna'],       4.6, false),
('Pandit Hardik Bhai',            'ahmedabad', '+917901001009', '+917901001009', 20, array['Gujarati','Hindi'],           array['mangal-shanti','satya-narayan-katha','hanuman-puja'],        5.0, true),
('Vedic Vidhya Kendra',           'ahmedabad', '+917901001010', '+917901001010', 40, array['Gujarati','Sanskrit','Hindi'],array['kemdruma-shanti','chandra-shanti','budha-shanti'],           4.7, true),
-- Varanasi
('Shiv Shakti Rudraksha Peeth',   'varanasi',  '+915421001001', '+915421001001', 40, array['Hindi','Sanskrit'],           array['rudra-abhishek','maha-mrityunjaya-jaap','kaal-sarp-shanti'],4.9, true),
('Dr Mukesh Kumar Dubey',         'varanasi',  '+915421001002', null,            35, array['Hindi','Sanskrit','English'], array['navagraha-shanti','grahan-dosh-nivaran','surya-aradhana'],  4.9, true),
('Kashi Vishwanath Darshan Kendra','varanasi', '+915421001003', '+915421001003', 50, array['Hindi','Sanskrit'],           array['rudra-abhishek','maha-mrityunjaya-jaap','chandi-homam'],    4.7, true),
('Kashi Purohit Service',         'varanasi',  '+915421001004', '+915421001004', 30, array['Hindi','Sanskrit','Bhojpuri'],array['pitra-tarpan','pitra-dosh-nivaran','surya-aradhana'],        4.8, true),
('Pandit Pranjal Dwivedi',        'varanasi',  '+915421001005', null,            28, array['Hindi','Sanskrit'],           array['mangal-shanti','sade-sati-shanti','navagraha-shanti'],       5.0, true),
('Pt. Omkar Nath Shastri',        'varanasi',  '+915421001006', '+915421001006', 45, array['Hindi','Sanskrit'],           array['durga-saptashati','vishnu-sahasranama','sudarshana-homam'], 4.9, true),
('Acharya Varun',                 'varanasi',  '+915421001007', '+915421001007', 22, array['Hindi','Sanskrit','English'], array['guru-chandal-shanti','kemdruma-shanti','guru-puja'],         4.7, false),
('Pandit Ratnesh',                'varanasi',  '+915421001008', null,            18, array['Hindi','Sanskrit'],           array['kaal-sarp-shanti','rahu-shanti','ketu-shanti'],              4.6, true),
('Ganga Aarti Samiti',            'varanasi',  '+915421001009', '+915421001009', 60, array['Hindi','Sanskrit'],           array['satya-narayan-katha','ayushya-homam','griha-pravesh'],       5.0, true),
('Pandit Kameshwar',              'varanasi',  '+915421001010', '+915421001010', 38, array['Hindi','Sanskrit','English'], array['grahan-dosh-nivaran','maha-mrityunjaya-jaap','pitra-dosh-nivaran'],4.8, true),
-- Prayagraj
('Pandit Rohit Shukla',           'prayagraj', '+915321001001', '+915321001001', 20, array['Hindi','Sanskrit'],           array['pitra-tarpan','pitra-dosh-nivaran','navagraha-shanti'],     4.7, true),
('Pandit Pradeep Pandey',         'prayagraj', '+915321001002', null,            18, array['Hindi','Sanskrit'],           array['mangal-shanti','kaal-sarp-shanti','sade-sati-shanti'],       4.6, true),
('Annapoorna Vaidik Kendra',      'prayagraj', '+915321001003', '+915321001003', 25, array['Hindi','Sanskrit'],           array['satya-narayan-katha','ganapathi-homam','griha-pravesh'],    4.6, true),
('Takshak Teerth Services',       'prayagraj', '+915321001004', '+915321001004', 30, array['Hindi','Sanskrit'],           array['pitra-tarpan','rudra-abhishek','maha-mrityunjaya-jaap'],    4.4, true),
('Pandit Sri Hari Jagannatha',    'prayagraj', '+915321001005', null,            35, array['Hindi','Sanskrit','Maithili'],array['pitra-tarpan','pitra-dosh-nivaran','vishnu-sahasranama'],   4.2, true),
('Acharya Dwivedi',               'prayagraj', '+915321001006', '+915321001006', 28, array['Hindi','Sanskrit'],           array['navagraha-shanti','sade-sati-shanti','grahan-dosh-nivaran'],4.8, true),
('Pandit Vishvambhar',            'prayagraj', '+915321001007', null,            22, array['Hindi','Sanskrit'],           array['vastu-shanti','griha-pravesh','ganapathi-homam'],            4.5, false),
('Pt. Anand Shastri',             'prayagraj', '+915321001008', '+915321001008', 32, array['Hindi','Sanskrit','English'], array['guru-chandal-shanti','kemdruma-shanti','guru-puja'],         4.9, true),
('Prayag Sangam Purohit',         'prayagraj', '+915321001009', '+915321001009', 40, array['Hindi','Sanskrit'],           array['pitra-tarpan','satya-narayan-katha','surya-aradhana'],       4.7, true),
('Sanskar Poojan',                'prayagraj', '+915321001010', null,            15, array['Hindi','Sanskrit'],           array['griha-pravesh','mangal-shanti','hanuman-puja'],              3.5, false)
on conflict do nothing;
